__BASE__: configs/CIFAR10/GQ-Nets/vgg7_2bits.yaml
BATCH_SIZE_PER_GPU: &bs 128

## Dataset
data:
  dataset:
    args:
      root: /home/lirundong/HDD1/Datasets/CIFAR
      download: true
  train_loader_conf:
    batch_size: *bs
  train_sampler_conf:
    batch_size: *bs
  val_loader_conf:
    batch_size: *bs

## Optimization
param_group:
  conf:
    - type: Adam
      args: &weight_group
        lr: !!float 4e-4
        weight_decay: !!float 1e-4
    - type: Adam
      args: &quant_param_group
        lr: !!float 1e-4
        weight_decay: 0.0
  groups:
    - <<: *weight_group
    - <<: *quant_param_group
  args:
    ft_layers: null
opt:
  args:
    alter_step: null  # jointly optimize W and Theta
schedule:
  args:
    batch_size: *bs

## Resume and snapshot
ckpt:
  dir: /home/lirundong/HDD1/quant-prob/cifar10/vgg7/2bits_small_lr_joint_train_cutout_on_tensor/checkpoints/

## Logging and diagnose
log:
  tb_dir: /home/lirundong/HDD1/quant-prob/cifar10/vgg7/2bits_small_lr_joint_train_cutout_on_tensor/tb_logs/
  file: /home/lirundong/HDD1/quant-prob/cifar10/vgg7/2bits_small_lr_joint_train_cutout_on_tensor/train
