# dataset
dataset:
  name: ImageNet
  args:
    root_dir: /mnt/lustre/share/images
    color: true
train_data_conf:
  batch_size: &n 256
  shuffle: false
  pin_memory: true
  num_workers: 2
train_samper_conf:
  batch_size: *n
  total_epoch: &e 65
val_data_conf:
  batch_size: *n
  shuffle: false
  pin_memory: true
  num_workers: 2

# validation setting
eval_iter: 625
eval_vis: false

# models
arch: resnet18
arch_conf:
  distillation: false
  quant_mode: STE
  denoise_mode: false
  quant_conf:
    bit_width: 4
  denoise_conf:
    inplace: true
    softmax: false

# optimizers
opt: Adam
opt_prob: false
denoise_only: false
opt_conf:
  lr: !!float 1e-2
  weight_decay: !!float 1e-5

# scheduler
epochs: *e
scheduler_conf:
  milestones: [50, 60]
  gamma: 0.1
  batch_size: *n

# checkpoint
save_iter: 5000
checkpoint_dir: /mnt/lustre/lirundong/Data/quant-prob/res18_ste_4bits_distillation/checkpoints

# logging
log_iter: 50
vis_iter: 625
tb_dir: /mnt/lustre/lirundong/Data/quant-prob/res18_ste_4bits_distillation/tb_logs

# resume
resume_path: /mnt/lustre/lirundong/Data/torchvision/resnet18-5c106cde.pth
resume_opt: false
reset_p: false

# distillation
distillation: true
soft_weight: 0.7
temperature: 2.0

# misc
comment: "ste_2bits"
update_bn: false
