__BASE__: configs/ImageNet/IDQ/res18_e120_b64x32_vanilla.yaml

arch:
  args:
    kw: 5
    ka: 5

opt:
  args:
    alter_step: -1

schedule:
  args:
    scheduled_variables:
      - ["soft_w", 1.0, 1.0, null, null, -1]
      - ["hard_w", 1.0, 1.0, null, null, -1]
      - ["ref_w", 1.0, 1.0, null, null, -1]

ckpt:
  dir: /mnt/lustre/lirundong/Data/quant-prob/imgnet/res18/e120_b64x32_w5a5_vanilla/checkpoints/

log:
  tb_dir: /mnt/lustre/lirundong/Data/quant-prob/imgnet/res18/e120_b64x32_w5a5_vanilla/tb_logs
  file: /mnt/lustre/lirundong/Data/quant-prob/imgnet/res18/e120_b64x32_w5a5_vanilla/train
