## Common args
BATCH_SIZE_PER_GPU: &bs 128
TOTAL_EPOCHS: &e 30

## Dataset
data:
  dataset:
    type: ImageNetST
    args:
      img_dir: /mnt/lustre/share/images/
      meta_dir: /mnt/lustre/lirundong/Data/Meta/imagenet_dev/
      color: true
  train_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 2
  train_sampler_conf:
    batch_size: *bs
    total_epoch: *e
  val_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 2

## Strategy
distil:
  mode: inv_distil # {null, inv_distil, distil}
  soft_w: 0.5
  hard_w: 0.5
  alter_step: &alter_n 1

quant:
  bitwidth:
    w: &qw 4
    a: &qa 4
  calib:
    steps: 5
    gamma: !!float 0.999
  enable_at: &enable_q begin
  align_zero: &qz true
  all_layers: &q_all true

## Models
arch:
  type: resnet18_idq
  args:
    kw: *qw
    ka: *qa
    quant_all: *q_all
    align_zero: *qz
    num_classes: 200
  sync_bn: true

## Evaluation
eval:
  freq: 300
  vis: false
  quant: false
  calibrate: false

loss:
  type: InvDistilLoss
  args:
    soft_weight: null
    temperature: 1.0
  topk: [1, 5]

## Optimization
param_group:
  conf:
    - type: SGD
      args: &sgd_args
        lr: 0.005
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
    - type: Adam
      args: &adam_args
        lr: 0.001
        weight_decay: 0.0
  groups:
    - <<: *sgd_args
    - <<: *adam_args
  args:
    ft_layers: null

opt:
  args:
    alter_step: *alter_n

schedule:
  args:
    milestones: [15, 25]
    gamma: 0.1
    batch_size: *bs
    warmup_epochs: 2
    warmup_lr: 0.005
    enable_quant_at: *enable_q

## Resume and snapshot
ckpt:
  freq: 1000
  dir: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/idq_ft/checkpoints/

resume:
  # path: /mnt/lustre/lirundong/Data/torchvision/resnet18-5c106cde.pth
  path: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/baseline_ft/checkpoints/ckpt_final.pth
  load_opt: false

## Diagnose
log:
  freq: 25
  tb_dir: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/idq_ft/tb_logs/
  file: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/idq_ft/train

diagnose:
  enabled: false
  diagnoser:
    type: null
    args: {}
  tasks: []

## Misc
comment: "idq_ft"
progress_bar: false
