## Common args
BATCH_SIZE_PER_GPU: &bs 128
TOTAL_EPOCHS: &e 90

## Dataset
data:
  dataset:
    type: ImageNetST
    args:
      img_dir: /mnt/lustre/share/images/
      meta_dir: /mnt/lustre/lirundong/Data/Meta/imagenet_dev/
      color: true
  train_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 2
  train_sampler_conf:
    batch_size: *bs
    total_epoch: *e
  val_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 1

## Strategy
distil:
  mode: inv_distil # {null, inv_distil, distil}
  soft_w: 0.5
  hard_w: 0.5
  alter_step: &alter_n 1
  zero_momentum: false

quant:
  bitwidth:
    w: &qw 1
    a: &qa 4
  calib:
    steps: 5
    gamma: !!float 0.999
    required_on_training: true
    update_bn: true
  enable_at: &enable_q begin # TODO: 0
  enable_fp: true
  align_zero: &qz false  # TODO: correct gradients for align_zero=True
  fp_layers: &fp_layers
    - conv1
    - fc

## Models
arch:
  type: resnet18_idq
  args:
    kw: *qw
    ka: *qa
    fp_layers: *fp_layers
    align_zero: *qz
    num_classes: 200
  sync_bn: false

## Evaluation
eval:
  freq: 100
  vis: false
  quant: true
  calibrate: false
  use_ema_stat: true

loss:
  type: InvDistilLoss
  args:
    soft_weight: null
    temperature: 1.0
  topk: [1, 5]

## Optimization
param_group:
  conf:
    - type: SGD
      args: &sgd_args
        lr: 0.05
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
    - type: Adam
      args: &adam_args
        lr: 0.001
        weight_decay: 0.0
  groups:
    - <<: *sgd_args
    - <<: *adam_args
  args:
    ft_layers: null

opt:
  args:
    alter_step: *alter_n

schedule:
  args:
    milestones: [30, 60]
    gamma: 0.1
    batch_size: *bs
    warmup_epochs: 4
    warmup_lr: 0.05
    enable_quant_at: *enable_q
    scheduled_variables:
      # fields: name, init_value, target_value, warmup_start_epoch, warmup_done_epoch
      # warmup_{...}_epoch is the index of `schedule.milestones`, setup to null means do not tune it
      - ["soft_w", 0.5, 0.5, null, null]
      - ["hard_w", 0.5, 0.5, null, null]

## Resume and snapshot
ckpt:
  freq: 1000
  dir: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/binary_idq_not_quant_all/checkpoints/

resume:
  path: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/baseline/checkpoints/ckpt_final.pth  # TODO: null
  load_opt: false

## Diagnose
log:
  freq: 25
  tb_dir: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/binary_idq_not_quant_all/tb_logs/
  file: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/binary_idq_not_quant_all/train

diagnose:
  enabled: false
  diagnoser:
    type: null
    args: {}
  tasks: []

## Misc
comment: "binary_idq_not_quant_all"
progress_bar: false
