## Common args
BATCH_SIZE_PER_GPU: &bs 128
TOTAL_EPOCHS: &e 150

## Dataset
data:
  dataset:
    type: ImageNetST
    args:
      img_dir: /mnt/lustre/share/images/
      meta_dir: /mnt/lustre/lirundong/Data/Meta/imagenet_dev/
      color: true
  train_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 2
  train_sampler_conf:
    batch_size: *bs
    total_epoch: *e
  val_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 1

## Strategy
distil:
  mode: inv_distil # {null, inv_distil, distil}
  soft_w: 0.5
  hard_w: 0.5
  alter_step: &alter_n 1
  zero_momentum: false

quant:
  bitwidth:
    w: &qw 4
    a: &qa 4
  calib:
    steps: 5
    gamma: !!float 0.999
    required_on_training: true
  enable_at: &enable_q 0
  enable_fp: true
  align_zero: &qz false  # TODO: correct gradients for align_zero=True
  fp_layers: &fp_layers
    - conv1
    - fc

## Models
arch:
  type: resnet18_idq
  args:
    kw: *qw
    ka: *qa
    fp_layers: *fp_layers
    align_zero: *qz
    num_classes: 200
  sync_bn: true

## Evaluation
eval:
  freq: 1000
  vis: false
  quant: true
  calibrate: false

loss:
  type: InvDistilLoss
  args:
    soft_weight: null
    temperature: 1.0
  topk: [1, 5]

## Optimization
param_group:
  conf:
    - type: SGD
      args: &sgd_args
        lr: 0.05
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
    - type: Adam
      args: &adam_args
        lr: 0.001
        weight_decay: 0.0
  groups:
    - <<: *sgd_args
    - <<: *adam_args
  args:
    ft_layers: null

opt:
  args:
    alter_step: *alter_n

schedule:
  args:
    milestones: [30, 90]
    gamma: 0.1
    batch_size: *bs
    warmup_epochs: 4
    warmup_lr: 0.2
    enable_quant_at: *enable_q
    scheduled_variables:
      # fields: name, init_value, target_value, warmup_start_epoch, warmup_done_epoch
      # warmup_{...}_epoch is the index of `schedule.milestones`
      # set to `null` means use init_value for FP training, target_value for Q training
      - ["soft_w", 0.0, 0.5, null, null]
      - ["hard_w", 1.0, 0.5, null, null]

## Resume and snapshot
ckpt:
  freq: 1000
  dir: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/idq_not_quant_all_idqx2/checkpoints/

resume:
  path: null
  load_opt: true

## Diagnose
log:
  freq: 25
  tb_dir: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/idq_not_quant_all_idqx2/tb_logs/
  file: /mnt/lustre/lirundong/Data/quant-prob/tiny_imgnet/res18/idq_not_quant_all_idqx2/train

diagnose:
  enabled: false
  diagnoser:
    type: null
    args: {}
  tasks: []

## Misc
comment: "idq_not_quant_all_idqx2"
progress_bar: false
