__BASE__: configs/ImageNet/IDQ/res18_e120_b64x32_vanilla.yaml

data:
  dataset:
    args:
      img_dir: /home/lirundong/HDD1/Datasets/imgnet/
      meta_dir: /home/lirundong/HDD1/Datasets/imgnet/meta/
  val_loader_conf:
    shuffle: true

param_group:
  conf:
    - type: SGD
      args: &sgd_args
        lr: 0.025
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
      schedules:
        - name: &weight_warmup weight_warmup
          type: LambdaLR
          args:
            # linear scaling in beginning 4 epochs, b64x32
            lr_lambda: "lambda step: 0.25 + 0.75 * step / (1281167 / 64 / 32 * 4)"
        - name: &weight_decay weight_decay
          type: MultiStepLR
          args:
            milestones: [60, 90]
            gamma: 0.1
    - type: Adam
      args: &adam_args
        lr: 0.0001  # smaller LR
        weight_decay: 0.0
  groups:
    - <<: *sgd_args
      scale_lr_by_world_size: true
    - <<: *adam_args
  args:
    ft_layers: null
schedule:
  quant_start_iter: 0
  dynamic_variable_scale: 1.0
  variable_cfgs:
    - ["soft_w", 0.5]
    - ["hard_w", 0.5]
    - ["ref_w", 0.0]
  opt_cfgs:
    - [*weight_warmup, 0, 4, "iter"]
    - [*weight_decay, 0, -1, "epoch"]

resume:
  path: /home/lirundong/HDD1/Models/IDQ/resnet18_w4a4_vanilla/ckpt_final.pth
  load_opt: false
  load_scheduler: false

ckpt:
  dir: /home/lirundong/HDD1/quant-prob/imgnet/res18/e120_b64x32_w4a4_vanilla/checkpoints/

log:
  tb_dir: /home/lirundong/HDD1/quant-prob/imgnet/res18/e120_b64x32_w4a4_vanilla/tb_logs
  file: /home/lirundong/HDD1/quant-prob/imgnet/res18/e120_b64x32_w4a4_vanilla/train

vis_path: /home/lirundong/HDD1/quant-prob/imgnet/res18/e120_b64x32_w4a4_vanilla/pre_acts/all_layers.npz
vis_names: []
