# dataset
dataset:
  name: ImageNet
  args:
    root_dir: /mnt/lustre/share/images
    color: true
train_data_conf:
  batch_size: &n 64
  shuffle: false
  pin_memory: true
  num_workers: 2
train_samper_conf:
  batch_size: *n
  total_epoch: &e 90
val_data_conf:
  batch_size: *n
  shuffle: false
  pin_memory: true
  num_workers: 1

# validation setting
eval_iter: 625
eval_vis: false

# models
arch: resnet18_idq
arch_conf:
  bit_width: 4

# optimizers
opt: SGD
opt_conf:
  lr: 0.2
  momentum: 0.9
  weight_decay: !!float 1e-4
  nesterov: true

# scheduler
epochs: *e
scheduler_conf:
  milestones: [30, 60]
  gamma: 0.1
  batch_size: *n
  warmup_epochs: 2
  warmup_lr: 0.01

# checkpoint
save_iter: 625
checkpoint_dir: /mnt/lustre/lirundong/Data/quant-prob/res18_i4_inv_distil/checkpoints

# logging
log_iter: 50
# vis_iter: 625
# tb_dir: /mnt/lustre/lirundong/Data/quant-prob/res18_i4_inv_distil/tb_logs

# resume
# resume_path: /mnt/lustre/lirundong/Data/torchvision/resnet18-5c106cde.pth

# distillation
distillation: false
soft_weight: 0.25  # TODO: check this?
temperature: 2.0
inv_distillation: true
calibration_steps: !!int 25
calibration_gamma: !!float 0.999

# misc
comment: "i4_inv_distil"
update_bn: false
