# dataset
dataset:
  name: ImageNet
  args:
    root_dir: /mnt/lustre/share/images
    color: true
train_data_conf:
  batch_size: &n 128
  shuffle: false
  pin_memory: true
  num_workers: 2
train_samper_conf:
  batch_size: *n
  total_epoch: &e 60
val_data_conf:
  batch_size: *n
  shuffle: false
  pin_memory: true
  num_workers: 1

# validation setting
eval_iter: &eval_n 625
eval_vis: false

# models
arch: resnet18_idq
arch_conf:
  bit_width: 4
  quant_all: true
  align_zero: false

# loss
loss: InvDistilLoss
loss_args:
  soft_weight: 0.25
  temperature: 1.0
  soft_loss_type: "KL"

# optimizers
# warmup: LR 0.2 -> 0.8 in 4 epochs
weight_opt: SGD
weight_conf:
  lr: 0.05
  momentum: 0.9
  weight_decay: !!float 1e-4
  nesterov: true

quant_param_opt: Adam
quant_param_conf:
  lr: 0.001
  weight_decay: 0.0

# scheduler
epochs: *e
scheduler_conf:
  milestones: [30, 45]
  gamma: 0.1
  batch_size: *n
  warmup_epochs: 4
  warmup_lr: 0.2

# checkpoint
save_iter: *eval_n
checkpoint_dir: /mnt/lustre/lirundong/Data/quant-prob/res18_baseline_scratch/checkpoints

# logging
log_iter: 50
# vis_iter: 625
tb_dir: /mnt/lustre/lirundong/Data/quant-prob/res18_baseline_scratch/tb_logs

# resume
# resume_path: /mnt/lustre/lirundong/Data/torchvision/resnet18-5c106cde.pth
# resume_path: /mnt/lustre/lirundong/Data/quant-prob/res18_baseline_scratch/checkpoints/ckpt_2019-05-09_16:24:57_final.pth
# resume_opt: true

# distillation
distillation: false
inv_distillation: true
calibration_steps: 25
calibration_gamma: !!float 0.999

# misc
comment: "from_scratch"
update_bn: false
topk: [1, 5]
loss_divisor: 1
quant_enable_step: 0 # disable quant loss
