BATCH_SIZE_PER_GPU: &bs 100
TOTAL_EPOCHS: &e 300

## Dataset
data:
  dataset:
    type: CIFAR10
    args:
      root: /mnt/lustre/lirundong/Data/Datasets/CIFAR
  train_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 2
  train_sampler_conf:
    batch_size: *bs
    total_epoch: *e
  val_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 1

## Models
arch:
  type: resnet18_idq
  args:
    kw: 2
    ka: 2
    align_zero: false
    use_multi_domain: true
    num_classes: 10
  gpu_per_model: 1
teacher_arch: null

## Loss
loss:
  type: InvDistilLoss
  args:
    soft_weight: null
    temperature: 1.0
    detach_ref: true
  topk: [1, 5]

## Optimization
param_group:
  conf:
    - type: Adam
      args: &weight_group
        lr: !!float 1e-3
        weight_decay: 0.0
      schedules:
        - name: &weight_lr_schedule1 weight_lr_annealing
          type: CosineAnnealingLR
          args:
            T_max: 25000 # number of iterations of final 50 epochs with 100 batch size
    - type: Adam
      args: &quant_param_group
        lr: !!float 1e-4
        weight_decay: 0.0
  groups:
    - <<: *weight_group
    - <<: *quant_param_group
  args:
    ft_layers: null
opt:
  args:
    alter_step: null  # jointly optimize W and Theta
schedule:
  quant_start_iter: 0
  dynamic_variable_scale: 1.0
  variable_cfgs:
    - ["soft_w", "soft_loss"]
    - ["hard_w", "hard_loss"]
    - ["ref_w", 0.0]
  opt_cfgs:
    - [*weight_lr_schedule1, 250, -1, "iter"]

## Evaluation
eval:
  freq: 1000
  vis: false
  quant: true
  calibrate: false

## Resume and snapshot
ckpt:
  freq: 1000000
  dir: /mnt/lustre/lirundong/Data/quant-prob/cifar10/resnet18/2bits_dymic/checkpoints/
resume:
  path: null
  load_opt: true
  load_scheduler: true

## Logging and diagnose
log:
  freq: 500
  tb_dir: /mnt/lustre/lirundong/Data/quant-prob/cifar10/resnet18/2bits_dymic/tb_logs/
  file: /mnt/lustre/lirundong/Data/quant-prob/cifar10/resnet18/2bits_dymic/train
diagnose:
  enabled: false
  diagnoser:
    type: null
    args: {}
  tasks: []

## Misc
comment: "2bits_resnet18"
progress_bar: false
quant:
  enable_fp: true
  calib:
    steps: 5
    gamma: !!float 0.999
    required_on_training: true
    update_bn: false
distil:
  mode: inv_distil # {null, inv_distil, distil}
  zero_momentum: false
