__BASE__: null

model:
  name: resnet18
  args:
    pretrained: false
  input_size: [1, 3, 224, 224]

wrapper:
  name: ParametrizedQuantWrapper
  args:
    quant_conf:
      mode: linear
      bit_width: 4
      align_zero: false
    fp_layers:
      - ((module|model).)*conv1
      - ((module|model).)*fc

epochs: 120
work_flow:
  - ["train", 1]
  - ["val", 1]

train:
  data_loader:
    args:
      batch_size: 64
      shuffle: false
      pin_memory: true
      num_workers: 2
  optim_groups:
    - name: &n_q quant_params
      matchs:
        - .*(_lb|_ub)$
      optim_type: Adam
      args:
        lr: !!float 1e-3
        weight_decay: 0.0
    - name: &n_w weight_params
      matches:
        - .*
      optim_type: SGD
      args:
        lr: 0.025
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
  loss:
    name: CEKL
    args: {}
  lr_policies:
    - name: StepMultiOptim
      args:
        gamma: 0.1
        step: [60, 90]
        warmup: linear
        warmup_iters: 2500  # ~4 epochs on b64x32 setting
        warmup_ratio: 0.25
        scale_by_world_size: true
        by_epoch: true
        apply_to:
          - *n_w
  qat_policies:
    - name: EnableQuantAtIntervals
      args:
        quant_mode: quant
        granularity: epoch
        intervals: &q_intervals
          - [10, 60]
          - [65, 90]
          - [95, -1]
    - name: ConstantVariable
      args:
        name: ce_loss_weight
        value: 1.0
    - name: IntervalWarmupedVariable
      args:
        name: kl_loss_weight
        value: 1.0
        warmup_epochs: 5
        intervals: *q_intervals
    - name: ConstantVariable
      args:
        name: kl_temperature
        value: 1.0
    - name: OptimAlterStep
      args:
        apply_to:
          - *n_w
          - *n_q
        alter_freq: 1
        intervals: *q_intervals
  runtime_hooks: none  # modify this if runtime diagnosis is required

eval:
  data_loader:
    args:
      batch_size: 128
      shuffle: false
      pin_memory: true
      num_workers: 2
  metrics:
    - name: DistEvalTopK
      args:
        logits_names:
          - fp
          - quant
        topk: [1, 5]

dataset:
  name: ImageNetST
  args:
    img_dir: /mnt/lustre/share/images/
    meta_dir: /mnt/lustre/share/images/meta/
    color: true

pre_trained:
  before_bn_folding: /mnt/lustre/lirundong/Data/torchvision/resnet18-5c106cde.pth
  after_bn_folding: null
resume: null
