__BASE__: null

model:
  name: resnet18
  args:
    pretrained: false
  input_size: [1, 3, 224, 224]
  init: kaiming_normal

wrapper:
  name: ParametrizedQuantWrapper
  args:
    quant_conf:
      method: linear
      bit_width: 4
      align_zero: false
    do_fold_bn: false
    fp_layers: null # list with item like: ((module|model).)*conv1

epochs: 120
work_flow:
  - ["train", 1]
  - ["val", 1]

train:
  data_loader:
    args:
      batch_size: 64
      shuffle: false
      pin_memory: true
      num_workers: 2
  optim_groups:
    - name: &n_q quant_params
      matches:
        - .*(_lb|_ub)$
      optim_type: Adam
      args:
        lr: !!float 1e-3
        weight_decay: 0.0
    - name: &n_w weight_params
      matches:
        - .*
      optim_type: SGD
      args:
        lr: 0.025
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
  loss:
    name: CEKL
    args: {}
  metrics:
    - name: TopK
      args:
        logits_names:
          - fp
          - quant
        topk: [1, 5]
  lr_policies:
    - name: StepMultiOptim
      args:
        gamma: 0.1
        step: [60, 90]
        warmup: linear
        warmup_iters: 2500  # ~4 epochs on b2048 setting
        warmup_ratio: 0.25
        scale_by_world_size: true
        by_epoch: true
        apply_to:
          - *n_w
  qat_policies:
    - name: EnableQuantAtIntervals
      args:
        quant_mode: quant  # ("fp", "quant", "qw_fa", "fw_qa")
        granularity: epoch  # ("epoch", "iter")
        always_enable_fp: true
        intervals: &q_intervals
          - [25, 60]
          - [65, 90]
          - [95, -1]
        calibrate_cfg:
          name: calibration
          type: ActivationCalibration
          args:
            percentile: 0.99
    - name: ConstantVariable
      args:
        name: ce_loss_weight
        value: 1.0
    - name: IntervalWarmupedVariable
      args:
        name: kl_loss_weight
        value: 1.0
        warmup_iters: 2500
        intervals: *q_intervals
    - name: ConstantVariable
      args:
        name: kl_temperature
        value: 1.0
    - name: OptimAlterStep
      args:
        apply_to:
          - *n_w
          - *n_q
        alter_freq: 1
        intervals: *q_intervals
  ckpt_interval: 1

eval:
  data_loader:
    args:
      batch_size: 64
      shuffle: false
      pin_memory: true
      num_workers: 1
  metrics:
    - name: DistEvalTopK
      args:
        logits_names:
          - fp
          - quant
        topk: [1, 5]
  quant_mode:
    - fp
    - quant

runtime_hooks: null

log:
  interval: 200
  hooks:
    - type: EnhancedTBLoggerHook
    - type: TextLoggerHook

dataset:
  name: ImageNetST
  args:
    img_dir: /mnt/lustre/share/images/
    meta_dir: /mnt/lustre/share/images/meta/
    color: true

work_dir: /mnt/lustre/lirundong/Workspace/GQ-Nets/res18-base/
pre_trained: null
resume: null
