__BASE__: configs/GQ_Nets/resnet20_cifar10_vanilla_fpfl.yaml

work_dir: /home/lirundong/HDD1/Experiments/GQ-Nets/resnet20-cifar10-vanilla-fpfl-pretrained
resume: null
fresh_resume: /home/lirundong/HDD1/Experiments/resnet20-cifar10/epoch_200.pth
