__BASE__: configs/GQ_Nets/resnet18_vanilla.yaml

wrapper:
  name: ParametrizedQuantWrapper
  args:
    quant_conf:
      bit_width: 2

work_dir: /mnt/lustre/lirundong/Workspace/GQ-Nets/res18-vanilla-w2a2/
