__BASE__: configs/GQ_Nets/resnet18_base.yaml

epochs: 10
work_flow:
  - ["train", 1]
  - ["val", 1]

train:
  optim_groups:
    - name: &n_q quant_params
      matches:
        - .*(_lb|_ub)$
      optim_type: Adam
      args:
        lr: !!float 1e-3
        weight_decay: 0.0
    - name: &n_w weight_params
      matches:
        - .*
      optim_type: SGD
      args:
        lr: 0.0025
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
  metrics:
    - name: TopK
      args:
        logits_names:
          - quant
  lr_policies:
    - name: StepMultiOptim
      args:
        gamma: 0.1
        step: [60, 90]
        warmup: linear
        warmup_iters: 2500  # ~4 epochs on b64x32 setting
        warmup_ratio: 0.25
        scale_by_world_size: true
        by_epoch: true
        apply_to:
          - *n_w

eval:
  metrics:
    - name: DistEvalTopK
      args:
        logits_names:
          - fp
          - quant
          - qw_fa
        topk: [1, 5]
  quant_mode:
    - fp
    - quant

work_dir: /mnt/lustre/lirundong/Workspace/GQ-Nets/res18-ste/
