__BASE__: configs/GQ_Nets/resnet18_base.yaml

model:
  name: resnet18
  args:
    pretrained: false
    num_classes: 200

runtime_hooks: null

train:
  lr_policies:
    - name: StepMultiOptim
      args:
        gamma: 0.1
        step: [60, 90]
        warmup: linear
        warmup_iters: 800  # ~4 epochs on b64x8 setting
        warmup_ratio: 0.25
        scale_by_world_size: true
        by_epoch: true
        apply_to:
          - weight_params
  qat_policies:
    - name: EnableQuantAtIntervals
      args:
        quant_mode: quant  # ("fp", "quant", "qw_fa", "fw_qa")
        granularity: epoch  # ("epoch", "iter")
        always_enable_fp: true
        intervals: &q_intervals
          - [25, 60]
          - [65, 90]
          - [95, -1]
    - name: ConstantVariable
      args:
        name: ce_loss_weight
        value: 1.0
    - name: IntervalWarmupedVariable
      args:
        name: kl_loss_weight
        value: 1.0
        warmup_iters: 800
        intervals: *q_intervals
    - name: ConstantVariable
      args:
        name: kl_temperature
        value: 1.0
    - name: OptimAlterStep
      args:
        apply_to:
          - weight_params
          - quant_params
        alter_freq: 1
        intervals: *q_intervals

log:
  interval: 25

dataset:
  name: ImageNetST
  args:
    img_dir: /mnt/lustre/share/images/
    meta_dir: /mnt/lustre/lirundong/Data/Meta/imagenet_dev/
    color: true

work_dir: /mnt/lustre/lirundong/Workspace/GQ-Nets/res18-small-200/
resume: /mnt/lustre/lirundong/Workspace/GQ-Nets/res18-small-200/latest.pth
