__BASE__: null

model:
  name: resnet18
  args:
    num_classes: 10
    pretrained: false
  input_size: [1, 3, 32, 32]

wrapper:
  name: ParametrizedQuantWrapper
  args:
    quant_conf:
      mode: linear
      bit_width: 4
      align_zero: false
    do_fold_bn: false
    fp_layers: null # list with item like: ((module|model).)*conv1

epochs: 200
work_flow:
  - ["train", 1]
  - ["val", 1]

train:
  data_loader:
    args:
      batch_size: 128
      shuffle: true
      pin_memory: true
      num_workers: 2
  optim_groups:
    - name: &n_q quant_params
      matches:
        - .*(_lb|_ub)$
      optim_type: Adam
      args:
        lr: !!float 4e-4
        weight_decay: 0.0
    - name: &n_w weight_params
      matches:
        - .*
      optim_type: SGD
      args:
        lr: 0.1
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
  loss:
    name: CEKL
    args: {}
  metrics:
    - name: TopK
      args:
        logits_names:
          - fp
          - quant
        topk: [1, 5]
  lr_policies:
    - name: StepMultiOptim
      args:
        gamma: 0.1
        step: [80, 120]
        warmup: null
        scale_by_world_size: false
        by_epoch: true
        apply_to:
          - *n_w
  qat_policies:
    - name: EnableQuantAtIntervals
      args:
        quant_mode: quant
        granularity: epoch
        always_enable_fp: true
        intervals: &q_intervals
          - [30, 80]
          - [85, 120]
          - [125, -1]
    - name: ConstantVariable
      args:
        name: ce_loss_weight
        value: 1.0
    - name: ConstantVariable
      args:
        name: kl_loss_weight
        value: 1.0
    - name: ConstantVariable
      args:
        name: kl_temperature
        value: 1.0
    - name: OptimAlterStep
      args:
        apply_to:
          - *n_w
          - *n_q
        alter_freq: -1  # tune W and Theta in parallel
        intervals: *q_intervals
  ckpt_interval: 1

eval:
  data_loader:
    args:
      batch_size: 128
      shuffle: false
      pin_memory: true
      num_workers: 1
  metrics:
    - name: EvalTopK
      args:
        logits_names:
          - fp
          - quant
        topk: [1, 5]
  quant_mode:
    - fp
    - quant

runtime_hooks: null

log:
  interval: 200
  hooks:
    - type: TextLoggerHook
    - type: TensorboardLoggerHook

dataset:
  name: CIFAR10
  args:
    root: /home/lirundong/HDD1/Datasets/CIFAR/

work_dir: /home/lirundong/HDD1/Experiments/GQ-Nets/resnet18-cifar10
pre_trained: null
resume: /home/lirundong/HDD1/Experiments/GQ-Nets/resnet18-cifar10/latest.pth
