__BASE__: configs/baselines/resnet20_cifar10.yaml

wrapper:
  name: ParametrizedQuantWrapper
  args:
    quant_conf:
      method: linear
      bit_width: 2
      align_zero: false
    do_fold_bn: false
    fp_layers: null # list with item like: ((module|model).)*conv1

train:
  optim_groups:
    - name: &n_q quant_params
      matches:
        - .*(_lb|_ub)$
      optim_type: Adam
      args:
        lr: !!float 4e-4
        weight_decay: 0.0
    - name: &n_w weight_params
      matches:
        - .*
      optim_type: SGD
      args:
        lr: 0.1
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
  metrics:
    - name: TopK
      args:
        logits_names:
          - fp
          - quant
        topk: [1, 5]
  qat_policies:
    - name: SetupQuantOnce
      args:
        quant_mode:
          - quant
          - fp
        calibrate_cfg:
          name: calibration
          type: ActivationCalibration
          args:
            percentile: 0.99
    - name: ConstantVariable
      args:
        name: ce_loss_weight
        value: 1.0
    - name: ConstantVariable
      args:
        name: kl_loss_weight
        value: 1.0
    - name: ConstantVariable
      args:
        name: kl_temperature
        value: 1.0
    - name: OptimAlterStep
      args:
        apply_to:
          - *n_w
          - *n_q
        alter_freq: -1  # tune W and Theta in parallel
        intervals:
          - [0, -1]
        loss_seq: &loss_seq
          - ce_loss
          - kl_loss

runtime_hooks:
  interval: 100
  hooks:
    - name: &c4_grad get_conv4_grad
      type: HijackGradient
      args:
        need_reg: true
        loss_seq: *loss_seq
        layers: ((module|model).)*layer3.2.conv2
  post_process:
    - name: multi_loss_grad_dist
      type: MultiLossGradDist
      args:
        metric: cosine
        apply_to: *c4_grad

eval:
  metrics:
    - name: EvalTopK
      args:
        logits_names:
          - fp
          - quant
        topk: [1, 5]
  quant_mode:
    - fp
    - quant

log:
  interval: 100
  hooks:
    - type: EnhancedTBLoggerHook
    - type: TextLoggerHook

work_dir: /home/lirundong/HDD1/Experiments/GQ-Nets/resnet20-cifar10-vanilla
