__BASE__: configs/GQ_Nets/resnet20_cifar10_vanilla.yaml

wrapper:
  name: ParametrizedQuantWrapper
  args:
    quant_conf:
      bit_width: 5

dataset:
  name: CIFAR10
  args:
    root: /mnt/lustre/lirundong/Data/Datasets/CIFAR

work_dir: /mnt/lustre/lirundong/Data/Experiments/GQ-Nets/resnet20-cifar10-vanilla-w5a5
resume: null
