__BASE__: configs/GQ_Nets/resnet18_base.yaml

wrapper:
  args:
    quant_conf:
      prune_to_zero: true

runtime_hooks:
  interval: 5
  hooks:
    - name: &fp_act fp_activations
      type: SaveAllValue
      args:
        target_cls: (Conv[\d]d|Linear)
        inject_at_mode: fp
    - name: &quant_act quant_activations
      type: SaveAllValue
      args:
        target_cls: (Conv[\d]d|Linear)
        inject_at_mode: quant
  post_process:
    - name: relative_error_vis
      type: RelativeErrorPostProcess
      args:
        apply_to:
          - *fp_act
          - *quant_act
        ce_loss_from: quant
        abnormal_x_ub: null # 1.0
        abnormal_y_lb: null # 10.0

eval:
  data_loader:
    args:
      batch_size: 32
  metrics:
    - name: EvalTopK
      args:
        logits_names:
          - fp
          - quant
        topk: [1, 5]

log:
  interval: 5
  hooks:
    - type: EnhancedTBLoggerHook
      exit_after_one_plot: true

dataset:
  name: ImageNetST
  args:
    img_dir: /home/lirundong/HDD1/Datasets/ILSVRC2012/
    meta_dir: /home/lirundong/HDD1/Datasets/ILSVRC2012/c200_meta_with_c1000_labels/  # 100k train, 10k val

work_dir: /home/lirundong/HDD1/Experiments/GQ-Nets/res18_e120_b64x32_qa_seg_sw_detach_kl_w1.0_multi_domain/
pre_trained: /home/lirundong/HDD1/Experiments/GQ-Nets/res18_e120_b64x32_qa_seg_sw_detach_kl_w1.0_multi_domain/pre_trained.pth  # model weights
resume: /home/lirundong/HDD1/Experiments/GQ-Nets/res18_e120_b64x32_qa_seg_sw_detach_kl_w1.0_multi_domain/resume.pth  # quant params
