# dataset
dataset:
  name: CIFAR10
  args:
    root: /mnt/lustre/lirundong/Data/Datasets/CIFAR
train_data_conf:
  batch_size: &n 256
  shuffle: false
  pin_memory: true
  num_workers: 2
train_samper_conf:
  batch_size: *n
  total_epoch: &e 10

# validation setting
eval_iter: 250
eval_vis: true
val_data_conf:
  batch_size: *n
  shuffle: false
  pin_memory: true
  num_workers: 1

# models
arch: cifar10_opt_bounds
arch_conf:
  num_classes: 10
  bit_width: 4  # TODO: recover this to 2

# optimizers
opt: SGD
opt_prob: false
denoise_only: false
bounds_only: true
opt_conf:
  lr: !!float 1e-3

# scheduler
epochs: *e
scheduler_conf:
  milestones: [220]
  gamma: 0.1
  batch_size: *n

# checkpoint
save_iter: 1000000
checkpoint_dir: /mnt/lustre/lirundong/Data/quant-prob/cifar10_2bits_opt_bounds/checkpoints

# logging
log_iter: 50
vis_iter: 1000
tb_dir: /mnt/lustre/lirundong/Data/quant-prob/cifar10_2bits_opt_bounds/tb_logs

# resume
resume_path: /mnt/lustre/lirundong/Data/quant-prob/LR_CIFAR10/checkpoints/checkpoint_final_best.pth
resume_opt: false
reset_p: false

# comment
comment: "2bits_opt_bounds"
distillation: false
update_bn: false
