## Common args
BATCH_SIZE_PER_GPU: &bs 64
TOTAL_EPOCHS: &e 120

## Dataset
data:
  dataset:
    type: ImageNetST
    args:
      img_dir: /mnt/lustre/share/images/
      meta_dir: /mnt/lustre/share/images/meta/
      color: true
  train_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 2
  train_sampler_conf:
    batch_size: *bs
    total_epoch: *e
  val_loader_conf:
    batch_size: *bs
    shuffle: false
    pin_memory: true
    num_workers: 1

## Strategy
distil:
  mode: null # {null, inv_distil, distil}
  alter_step: &alter_n null
  zero_momentum: false

quant:
  bitwidth:
    w: &qw 4
    a: &qa 4
  calib:
    steps: 25
    gamma: !!float 0.999
    required_on_training: true
  enable_at: &enable_q null # never enable
  enable_fp: true
  align_zero: &qz false
  fp_layers: &fp_layers null

## Models
arch:
  type: resnet50_idq
  args:
    kw: *qw
    ka: *qa
    fp_layers: *fp_layers
    align_zero: *qz
  sync_bn: false # true

## Evaluation
eval:
  freq: 1000
  vis: false
  quant: false
  calibrate: false

loss:
  type: CrossEntropyLoss
  args: {}
  topk: [1, 5]

## Optimization
param_group:
  conf:
    - type: SGD
      args: &sgd_args
        lr: 0.025
        momentum: 0.9
        weight_decay: !!float 1e-4
        nesterov: true
    - type: Adam
      args: &adam_args
        lr: 0.001
        weight_decay: 0.0
  groups:
    - <<: *sgd_args
    - <<: *adam_args
  args:
    ft_layers: null # IMPORTANT: tune all layers

opt:
  args:
    alter_step: *alter_n

schedule:
  args:
    milestones: [60, 90]
    gamma: 0.1
    batch_size: *bs
    warmup_epochs: 4
    warmup_lr: 0.2
    enable_quant_at: *enable_q
    scheduled_variables:
      # fields: name, init_value, target_value, warmup_start_epoch, warmup_done_epoch
      # warmup_{...}_epoch is the index of `schedule.milestones`
      # set to `null` means use init_value for FP training, target_value for Q training
      - ["soft_w", 0.0, 0.5, null, null]
      - ["hard_w", 1.0, 0.5, null, null]

## Resume and snapshot
ckpt:
  freq: 1000
  dir: /mnt/lustre/lirundong/Data/quant-prob/imgnet/res50/baseline/checkpoints/

resume:
  path: final
  load_opt: true

## Diagnose
log:
  freq: 25
  tb_dir: /mnt/lustre/lirundong/Data/quant-prob/imgnet/res50/baseline/tb_logs/
  file: /mnt/lustre/lirundong/Data/quant-prob/imgnet/res50/baseline/train

diagnose:
  enabled: false
  diagnoser:
    type: null
    args: {}
  tasks: []

## Misc
comment: "baseline_res50"
progress_bar: false
