__BASE__: configs/GQ_Nets/resnet20_cifar10.yaml

runtime_hooks:
  interval: 5
  hooks:
    - name: bc_layer_1_0_conv2
      type: ManualBiasCorrection
      args:
        target_layer: layer1.0.conv2
        target_conf: input
        relevant_bias: -1.0
    - name: &fp_act fp_activations
      type: SaveAllValue
      args:
        target_cls: (Conv[\d]d|Linear)
        inject_at_mode: fp
        var_names:
          - input
          - weight
          - pre_activation
          - output
    - name: &quant_act quant_activations
      type: SaveAllValue
      args:
        target_cls: (Conv[\d]d|Linear)
        inject_at_mode: quant
        var_names:
          - input
          - weight
          - pre_activation
          - output
  post_process:
    - name: relative_error_vis
      type: RelativeErrorPostProcess
      args:
        apply_to:
          - *fp_act
          - *quant_act
        ce_loss_from: quant
        abnormal_x_ub: null # 1.0
        abnormal_y_lb: null # 10.0

eval:
  data_loader:
    args:
      batch_size: 32
  metrics:
    - name: EvalTopK
      args:
        logits_names:
          - fp
          - quant
        topk: [1, 5]

log:
  interval: 5
  hooks:
    - type: EnhancedTBLoggerHook
      exit_after_one_plot: true

work_dir: /home/lirundong/HDD1/Experiments/GQ-Nets/resnet20-cifar10-diag-BC/
resume: /home/lirundong/HDD1/Experiments/GQ-Nets/resnet20-cifar10/latest.pth
