# dataset
dataset:
  name: ImageNet
  args:
    root_dir: /mnt/lustre/share/images
    color: true
train_data_conf:
  batch_size: &n 256
  shuffle: false
  pin_memory: true
  num_workers: 2
train_samper_conf:
  batch_size: *n
  total_epoch: &e 10
val_data_conf:
  batch_size: *n
  shuffle: false
  pin_memory: true
  num_workers: 1

# validation setting
eval_iter: &eval 100 # 625
eval_vis: false

# models
arch: resnet18
arch_conf:
  distillation: false
  quant_mode:
    conv: opt_bounds
    linear: opt_bounds
  denoise_mode: false
  quant_conf:
    bit_width: 6 # TODO: recover this!
  denoise_conf:
    inplace: true
    softmax: false

# optimizers
opt: SGD
opt_prob: false
denoise_only: false
bounds_only: true
opt_conf:
  lr: !!float 1e-3
  weight_decay: !!float 1e-4

# scheduler
epochs: *e
scheduler_conf:
  milestones: [50, 60]
  gamma: 0.1
  batch_size: *n

# checkpoint
save_iter: *eval
checkpoint_dir: /mnt/lustre/lirundong/Data/quant-prob/res18_ste_4bits_opt_bounds/checkpoints

# logging
log_iter: 50
vis_iter: 625
tb_dir: /mnt/lustre/lirundong/Data/quant-prob/res18_ste_4bits_opt_bounds/tb_logs

# resume
resume_path: /mnt/lustre/lirundong/Data/torchvision/resnet18-5c106cde.pth
# resume_path: /mnt/lustre/lirundong/Data/quant-prob/res18_ste_4bits_opt_bounds/checkpoints/ckpt_i8.pth
resume_opt: false
reset_p: false
reset_bounds: true

# distillation
distillation: true
soft_weight: 0.8
temperature: 2.0

# misc
comment: "opt_bonus_4bits"
update_bn: false
